name: Build and Test

on:
  push:
    branches:
      - master  # Replace 'main' with the name of your main branch

jobs:
  build:
    runs-on: self-hosted  # Use the label of your self-hosted runner here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Specify your desired Node.js version

    - name: Install dependencies
      run: npm install  # Use the appropriate command for your project

    - name: Build
      run: npm run build  # Use the appropriate build script

    - name: Test
      run: npm test  # Use the appropriate test script
